name = "broadwaykebab"
compatibility_date = "2024-01-15"

[build]
command = "npm run build"
publish = "out"

[build.environment_variables]
NODE_VERSION = "18"

# Static asset handling for Next.js
[[headers]]
for = "/_next/static/css/*"
[headers.values]
Content-Type = "text/css"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/_next/static/chunks/*"
[headers.values]
Content-Type = "application/javascript"
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Page redirects
[[redirects]]
from = "/menu"
to = "/menu/index.html"
status = 200

[[redirects]]
from = "/menu/"
to = "/menu/index.html"
status = 200

# Static file fallbacks
[[redirects]]
from = "/_next/static/css/*"
to = "/_next/static/css/:splat"
status = 200

[[redirects]]
from = "/_next/static/chunks/app/*"
to = "/_next/static/chunks/app/:splat"
status = 200

[[redirects]]
from = "/_next/static/chunks/*"
to = "/_next/static/chunks/:splat"
status = 200

# Catch-all fallback
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
